import classNames from 'classnames/bind';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { signIn, signOut, useSession } from 'next-auth/react';

import styles from '@/styles/Home.module.scss';

import { environment } from 'src/constants/env';

const cx = classNames.bind(styles);
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { status, data } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cx('main')}>
        <div className={cx('description')}>
          <p>{environment}</p>
          <div>
            {status === 'authenticated' && data.user ? (
              <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'center' }}>
                <img src={data.user.image as string} style={{ width: 50, height: 50 }} />
                <div>{data.user.name}</div>
                <button
                  onClick={() => {
                    signOut();
                  }}
                >
                  logout
                </button>
              </div>
            ) : (
              <button
                onClick={() => {
                  signIn('google');
                }}
              >
                login
              </button>
            )}
          </div>
        </div>

        <div className={cx('center')}>
          <Image
            className={cx('logo')}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={cx('grid')}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx('card')}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx('card')}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx('card')}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx('card')}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
