import classNames from 'classnames/bind';
import { useAtomValue, useSetAtom } from 'jotai';
import Head from 'next/head';
import Image from 'next/image';

import { Layout } from '@/components/Layout';
import { testReadOnlyAtom, testReadWriteAtom } from '@/stores/globalStore';
import styles from '@/styles/Home.module.scss';

import { environment } from 'src/constants/env';

const cx = classNames.bind(styles);

export default function Home() {
  const test = useAtomValue(testReadOnlyAtom);
  const setTest = useSetAtom(testReadWriteAtom);

  // const { data } = useGetUserQuery();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={cx('main')}>
          <p>{`Environment: ${environment}`}</p>
          {/* TODO: 테스트 용도 */}
          <div>
            <button
              style={{ marginTop: 20 }}
              onClick={() => setTest(false)}
            >{`useSetAtom 테스트: ${test}`}</button>
          </div>
          <div className={cx('center')}>
            <Image
              className={cx('logo')}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </div>

          <div className={cx('grid')}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={cx('card')}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Docs <span>-&gt;</span>
              </h2>
              <p>Find in-depth information about Next.js features and&nbsp;API.</p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={cx('card')}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Learn <span>-&gt;</span>
              </h2>
              <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={cx('card')}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Templates <span>-&gt;</span>
              </h2>
              <p>Discover and deploy boilerplate example Next.js&nbsp;projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={cx('card')}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Deploy <span>-&gt;</span>
              </h2>
              <p>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
            </a>
          </div>
        </div>
      </Layout>
    </>
  );
}
